server:
  port: 58081  # 서버 실행 포트 설정

springdoc:
  packages-to-scan: com.example.binancewebsocket  # Swagger에서 문서화할 패키지 경로 지정
  default-consumes-media-type: application/json;charset=UTF-8  # 기본 요청 데이터 타입
  default-produces-media-type: application/json;charset=UTF-8  # 기본 응답 데이터 타입
  swagger-ui:
    path: /api  # Swagger UI 접속 경로
    display-request-duration: true  # 요청 처리 시간 표시
    operations-sorter: alpha  # API 문서를 알파벳 순서로 정렬
  api-docs:
    path: /api  # Swagger API 문서 경로

spring:
  datasource:
    hikari:
      pool-name: ai_bot_pool  # HikariCP 커넥션 풀 이름
      minimum-idle: 10  # 최소 유지 커넥션 개수
      maximum-pool-size: 50  # 최대 커넥션 개수
      connection-timeout: 5000  # 커넥션 획득 타임아웃 (5초)

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 테이블 자동 업데이트 (운영 환경에서는 'none'으로 설정 추천)
    show-sql: true  # 실행되는 SQL 로그 출력 (운영에서는 false 권장)
    properties:
      hibernate:
        format_sql: true  # SQL 로그 가독성 향상

  logging:
    level:
      root: INFO  # 기본 로그 레벨 (DEBUG, INFO, WARN, ERROR)
      org.springframework.web: INFO  # Spring Web 관련 로그 자세히 출력
      com.example.binancewebsocket: INFO  # 프로젝트 패키지 내 로그 출력 레벨

  web:
    cors:
      allow-credentials: true  # 쿠키 및 인증 정보 포함 여부
      allowed-origin-patterns:
        - "http://localhost:3000"  # ⭐ 특정 출처만 허용 (보안 강화를 위해 "*" 사용 지양)
        - "*"
      allowed-methods: # 허용할 HTTP 메서드
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      exposed-headers:
        - Authorization
  task:
    scheduling:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # Snake Case -> Camel Case 자동 변환

dotenv:
  enabled: true

symbols: XRPUSDT

enable:
  binance:
    websocket: true
    scheduling: true
